# Generated by Django 4.2.1 on 2023-05-27 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('hypertenstion', 'Hypertenstion'), ('diabetes', 'Diabetes'), ('heart_attack', 'Heart Attack'), ('stroke', 'Stroke'), ('blood_clot', 'Blood Clot'), ('seizures', 'Seizures'), ('cancer', 'Cancer'), ('mental_illness', 'Mental Illness')], max_length=100, null=True)),
                ('when_diagnosed', models.CharField(blank=True, max_length=100, null=True)),
                ('intake_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.intakeform')),
            ],
        ),
    ]
